# Generated by Django 5.0.4 on 2024-04-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_gmail_verif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gmail_verif',
        ),
    ]
