# Generated by Django 5.0.4 on 2024-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_gmail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gmail_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
