# Generated by Django 5.0.4 on 2024-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='items',
            field=models.ManyToManyField(to='event.item'),
        ),
    ]
