# Generated by Django 5.0.4 on 2024-04-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_userevent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_detail', to='event.eventdetail'),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_img/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='event.event')),
            ],
        ),
    ]
