# Generated by Django 5.0.4 on 2024-04-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_userevent_event_detail_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='event',
        ),
    ]
