# Generated by Django 5.0.4 on 2024-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_item_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
