# Generated by Django 5.0.4 on 2024-04-11 11:27

import event.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_userevent_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='event/', validators=[event.validators.validate_svg]),
        ),
    ]
