# Generated by Django 5.0.4 on 2024-04-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
