# Generated by Django 5.0.4 on 2024-04-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_eventdetail_date_alter_eventdetail_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userevent',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
